---
  - name: Init Swarm Leader
    tags:
      - leader
    hosts: swarm-leader
    gather_facts: False
    
    tasks:
      - name: Wait 600 seconds for target connection to become reachable/usable
        wait_for_connection:

      - name: Init a new swarm with default parameters
        docker_swarm:
          state: present
          advertise_addr: "{{ inventory_hostname }}:2377"

      - name: Get Worker Token
        command: docker swarm join-token worker -q
        register: worker_token

      - name: Show Worker Token
        debug: var=worker_token.stdout

      - name: Master Token
        command: docker swarm join-token manager -q
        register: master_token

      - name: Show Master Token
        debug: var=master_token.stdout
  
  
  - name: Join Swarm Masters
    tags:
      - master
    hosts: swarm-masters
    gather_facts: FalseFalse
    vars:
      token: "{{ hostvars[groups['swarm-leader'][0]]['master_token']['stdout'] }}"
      master: "{{ hostvars[groups['swarm-leader'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Join Swarm Cluster as a Manager
        docker_swarm:
          state: join
          advertise_addr: "{{ inventory_hostname }}"
          join_token: "{{ token }}"
          remote_addrs: [ '{{ master }}:2377' ]  
        register: manager

  - name: Join Swarm Cluster
    tags:
      - worker
    hosts: swarm-workers
    gather_facts: False
    vars:
      token: "{{ hostvars[groups['swarm-leader'][0]]['worker_token']['stdout'] }}"
      master: "{{ hostvars[groups['swarm-leader'][0]]['inventory_hostname'] }}"
    tasks:
      - name: Wait 600 seconds for target connection to become reachable/usable
        wait_for_connection:

      - name: Join Swarm Cluster as a Worker
        docker_swarm:
          state: join
          advertise_addr: "{{ inventory_hostname }}"
          join_token: "{{ token }}"
          remote_addrs: [ '{{ master }}:2377' ]  
        register: worker
