version: '3.3'

services:
  traefik:
    image: traefik:v1.7
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    deploy:
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN}
        - traefik.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.domain=${DOMAIN}
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - swarm-net
    configs:
      - source: traefik-conf
        target: /etc/traefik/traefik.toml
      - source: domain-crt
        target: /certs/traefik.crt
      - source: domain-key
        target: /certs/traefik.key
configs:
  traefik-conf:
    external: true
  domain-crt:
    external: true
  domain-key:
    external: true
networks:
  swarm-net:
    external: true
